# Use `just <recipe>` to run a recipe
# https://just.systems/man/en/

# By default, run the `--list` command
default:
    @just --list

bash:
    #docker run -it --rm --volume .:/app --user $(id -u) node:12 bash
    #docker-compose run --rm dev bash -c "cd /app && bash"
    docker-compose exec dev bash -c "cd /app && bash"

dev:
    npm run dev
