# Crowdin configuration file
# see: https://support.crowdin.com/configuration-file/
#
# you will need the Java CLI client
# see: https://support.crowdin.com/cli-tool/

project_identifier: qownnotes

# the api key has to be provided by ~/.crowdin.yaml
#api_key: XXXX

files:
  -
    # source files filter
    source: '/src/languages/QOwnNotes_en.ts'
    # where translations live
    translation: '/src/languages/QOwnNotes_%locale_with_underscore%.ts'
    #translation: '/src/languages/QOwnNotes_%locale%.ts'
    #translation: 'src/languages/QOwnNotes_%two_letters_code%.ts'
    #"languages_mapping" : {
      #"two_letters_code" : {
        #"pt" : "pt_PT",
        #"pt-BR" : "pt_BR"
      #}
    #}
    "languages_mapping" : {
      "locale_with_underscore" : {
        "ar_SA" : "ar",
        "ca_ES" : "ca",
        "cs_CZ" : "cs",
        "de_DE" : "de",
        "es_ES" : "es",
        "fr_FR" : "fr",
        "hr_HR" : "hr",
        "hu_HU" : "hu",
        "it_IT" : "it",
        "ja_JP" : "ja",
        "nl_NL" : "nl",
        "pl_PL" : "pl",
        "ru_RU" : "ru",
        "uk_UA" : "uk",
        "zh_CN" : "zh"
      }
    }
