# Use `just <recipe>` to run a recipe
# https://just.systems/man/en/

# By default, run the `--list` command
default:
    @just --list

build:
    docker build -t qownnotes-ubuntu22-dev .

bash:
    docker run -it --rm qownnotes-ubuntu22-dev bash
