site_name: QOwnNotes Documentation
site_description: QOwnNotes - Plain-text file markdown note taking with Nextcloud integration
site_author: qownnotes.org
# needed for 404 error page and canonical urls
site_url: https://docs.qownnotes.org/en/latest
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/pbek/QOwnNotes'
edit_uri: 'edit/develop/docs/content'

docs_dir: 'content'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/img/qownnotes.icon.png
  logo: assets/img/qownnotes.logo.png
  feature:
    tabs: false
  palette:
    # https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
    # https://github.com/squidfunk/mkdocs-material/blob/eab7148337dc7f0e9304850b606a123da6b8d559/src/assets/stylesheets/application-palette.scss#L70-L90
    primary: 'blue-grey'
    accent: 'blue'
  i18n:
    prev: 'Previous'
    next: 'Next'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/pbek/QOwnNotes'
    - type: 'telegram'
      link: 'https://t.me/QOwnNotes'
    - type: 'twitter'
      link: 'https://twitter.com/QOwnNotes'
    - type: 'facebook'
      link: 'https://www.facebook.com/QOwnNotes/'
  disqus: 'qownnotes-docs'

copyright: "Copyright &copy; 2014-2020 Patrizio Bekerle"

google_analytics:
  - 'UA-52660882-4'
  - 'docs.qownnotes.org'

extra_css:
  - assets/styles/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mermaid@8.4.8/dist/mermaid.min.js

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # this doesn't work on ReadTheDocs, we need to use `<div class="mermaid"></div>` instead
#          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true

# Page tree
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started':
      - 'Concept': 'getting-started/concept.md'
      - 'Install QOwnNotes': 'getting-started/install-qownnotes.md'
      - 'Browser extension': 'getting-started/browser-extension.md'
      - 'QOwnNotesAPI': 'getting-started/qownnotesapi.md'
      - 'CLI parameters': 'getting-started/cli-parameters.md'
      - 'Shortcuts': 'getting-started/shortcuts.md'
  - 'Editor':
      - 'Spellchecking': 'editor/spellchecking.md'
      - 'Time formats': 'editor/time-formats.md'
  - 'Scripting':
      - 'Basics': 'scripting/index.md'
      - 'Methods and objects': 'scripting/methods-and-objects.md'
      - 'Hooks': 'scripting/hooks.md'
      - 'Exposed classes': 'scripting/classes.md'
  - 'Contributing':
      - 'Get involved': 'contributing/get-involved.md'
      - 'Maintainers': 'contributing/maintainers.md'
      - 'Translation': 'contributing/translation.md'
