name: qownnotes
version: git
version-script: cat src/version.h | sed "s/[^0-9,.]//g"
summary: Plain-text file markdown note taking with Nextcloud/ownCloud integration
grade: stable
confinement: strict
base: core18
description: |
  QOwnNotes is the open source (GPL) plain-text file markdown note taking app
  for GNU/Linux, Mac OS X and Windows, that (optionally) works together with the
  notes application of Nextcloud/ownCloud.
  https://www.qownnotes.org/

apps:
  qownnotes:
    command: desktop-launch $SNAP/usr/bin/QOwnNotes -style=Breeze --snap
    environment:
        DISABLE_WAYLAND: 1
        QT_QPA_PLATFORMTHEME: gtk3
    # see https://docs.snapcraft.io/reference/interfaces
    plugs:
      - x11
      - unity7
      - network
      - network-bind
      - home
#      - kde-frameworks-5-plug
      - desktop
      - desktop-legacy
      - removable-media
      - opengl
      - cups-control

# plugs:
#   kde-frameworks-5-plug:
#     content: kde-frameworks-5-all
#     interface: content
#     default-provider: kde-frameworks-5
#     target: kf5

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  qownnotes:
    source: .
#    source: https://github.com/pbek/qownnotes.git
    # see https://docs.snapcraft.io/reference/plugins/qmake
    plugin: qmake
    qt-version: qt5
    options:
      - ./src
      - CONFIG+=release
    build-packages:
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - libqt5websockets5-dev
      - libqt5x11extras5-dev
    stage-packages:
      - libqt5gui5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5widgets5
      - libqt5qml5
      - libqt5svg5
      - libqt5network5
      - libqt5xml5
      - libqt5xmlpatterns5
      - libqt5printsupport5
      - libqt5websockets5
      - libqt5x11extras5
      - qtwayland5
    stage:
      - -usr/share/pkgconfig
    after: [desktop-qt5]

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - build-essential
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
        - xdg-user-dirs
        - fcitx-frontend-qt5

  plasma-integration:
    plugin: nil
    stage-packages:
#    - plasma-integration # causes the KDE file selector to be used that didn't work
    - kde-style-breeze
    - breeze-icon-theme
#    - kio # runtime slaves for kio, but does not seem to work
    prime:
    - "-usr/share/wallpapers/*"
    - "-usr/share/fonts/*"

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme
