name: qownnotes
version: VERSION-STRING
summary: Plain-text file notepad with markdown support and ownCloud integration
confinement: strict
#confinement: devmode
description: |
  QOwnNotes is the open source (GPL) plain-text file notepad with markdown support 
  and todo list manager for GNU/Linux, Mac OS X and Windows, that (optionally) works 
  together with the notes application of ownCloud.
  http://www.qownnotes.org/

# Launchpad is complaining about the existance of the property `confinement`
#confinement: strict
#confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  qownnotes:
    command: desktop-launch $SNAP/usr/bin/QOwnNotes
    plugs:
      - x11
      - network
      - network-bind

parts:
  qownnotes:
    source: http://downloads.sourceforge.net/project/qownnotes/src/qownnotes-VERSION-STRING.tar.xz
    source-type: tar
    plugin: qmake
    qt-version: qt5
    build-packages:
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
    after: [desktop/qt5]
  env:
    plugin: nil
    stage-packages:
      - libqt5gui5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5widgets5
      - libqt5qml5
      - libqt5svg5
      - libqt5network5
      - libqt5xml5
      - libqt5printsupport5
      - libqt5declarative5
    after: [qt5conf]
